### ISSUE TITLE
Nova v4 support

### ISSUE THREAD

**Issue by matthewhutchings** [awesome-nova/filter-card#13]
Is this possible?

Error Message: 

TypeError: Cannot read properties of undefined (reading '_c')
    at Proxy.render (awesome-nova-filter-card:1:17354)
    at Fn (runtime-core.esm-bundler.js:888:44)
    at we.fn (runtime-core.esm-bundler.js:5600:57)
    at we.run (reactivity.esm-bundler.js:185:25)
    at R.e.update (runtime-core.esm-bundler.js:5714:56)
    at R (runtime-core.esm-bundler.js:5728:9)
    at j (runtime-core.esm-bundler.js:5510:9)
    at N (runtime-core.esm-bundler.js:5468:17)
    at g (runtime-core.esm-bundler.js:5058:21)
    at we.fn (runtime-core.esm-bundler.js:5607:21)

**Comment by dmitryvasilevskiy** [comment]
same error

**Comment by tumainimosha** [comment]
Plus one on this. 

I see we have an open PR on Nova 4 support here #12 which is yet to be merged

This would be a great addition to this very useful package, for those using Nova v4.
